## Introduction to numpy

In [1]:
import numpy as np

In [2]:
a1=np.array([1,2,3])

In [3]:
a1

array([1, 2, 3])

In [4]:
a1.shape

(3,)

In [5]:
a1.ndim

1

In [6]:
a1.dtype

dtype('int64')

In [7]:
type(a1)

numpy.ndarray

In [17]:
a2=np.array([[1,2,3],
             [4,5,6]])

In [18]:
a2 

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
a2.shape

(2, 3)

In [20]:
a2.ndim

2

In [29]:
a3=np.array([[[1,2,3],
             [4,5,6],
             [7,8,9]],
             [[10,11.0,12],
              [13,14,15],
              [16,17,18]]])

In [30]:
a3.ndim

3

In [31]:
a3.shape

(2, 3, 3)

In [32]:
a3.dtype

dtype('float64')

In [35]:
a4=np.array([[[1,2],
               [3,4]],
              [[5,6],
               [7,8]],
              [[9,10],
               [11,12]],
              [[13,14],
               [15,16]]])

In [36]:
a4

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16]]])

In [37]:
a4.shape

(4, 2, 2)

In [38]:
a4.ndim

3

In [39]:
import pandas as pd

In [44]:
df=pd.DataFrame(a2)

In [42]:
df

0  1  2
0  1  2  3
1  4  5  6