## Introduction to numpy

In [1]:
import numpy as np

In [2]:
a1=np.array([1,2,3])

In [3]:
a1

array([1, 2, 3])

In [4]:
a1.shape

(3,)

In [5]:
a1.ndim

1

In [6]:
a1.dtype

dtype('int64')

In [7]:
type(a1)

numpy.ndarray

In [8]:
a2=np.array([[1,2,3],
             [4,5,6]])

In [9]:
a2 

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
a2.shape

(2, 3)

In [11]:
a2.ndim

2

In [12]:
a3=np.array([[[1,2,3],
             [4,5,6],
             [7,8,9]],
             [[10,11.0,12],
              [13,14,15],
              [16,17,18]]])

In [13]:
a3.ndim

3

In [14]:
a3.shape

(2, 3, 3)

In [15]:
a3.dtype

dtype('float64')

In [16]:
a4=np.array([[[1,2],
               [3,4]],
              [[5,6],
               [7,8]],
              [[9,10],
               [11,12]],
              [[13,14],
               [15,16]]])

In [17]:
a4

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16]]])

In [18]:
a4.shape

(4, 2, 2)

In [19]:
a4.ndim

3

In [20]:
import pandas as pd

In [21]:
df=pd.DataFrame(a2)

In [22]:
df

0  1  2
0  1  2  3
1  4  5  6

## Arrays with numpy

In [23]:
ones=np.ones((2,3))

In [24]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [25]:
zeros=np.zeros((2,3))

In [26]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
range=np.arange(0,10,2)

In [28]:
range

array([0, 2, 4, 6, 8])

In [29]:
random_array=np.random.randint(0,5,(2,5))

In [30]:
random_array

array([[3, 3, 2, 3, 3],
       [3, 1, 4, 3, 4]])

In [31]:
random_array_1=np.random.random((5,3))

In [32]:
random_array_1

array([[0.07830922, 0.67302026, 0.96313581],
       [0.33755378, 0.41013508, 0.53221698],
       [0.08765635, 0.38991382, 0.20102926],
       [0.33851049, 0.58475904, 0.16751404],
       [0.00766716, 0.70709913, 0.15277411]])

In [33]:
random_array2=np.random.rand(5,2)

In [34]:
random_array2

array([[0.50821448, 0.34319963],
       [0.2618046 , 0.50630518],
       [0.74648991, 0.15008453],
       [0.54013154, 0.49224977],
       [0.27565555, 0.7513771 ]])

## Random Seed

In [35]:
np.random.seed(11)
random_seed=np.random.randint(10,size=(2,2))
random_seed

array([[9, 0],
       [1, 7]])

In [36]:
a1

array([1, 2, 3])

In [37]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
a3

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.]],

       [[10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]]])

In [39]:
a3.ndim

3

In [40]:
a3.size

18

In [41]:
a3.shape

(2, 3, 3)

In [42]:
a3[:2,:2,:2]

array([[[ 1.,  2.],
        [ 4.,  5.]],

       [[10., 11.],
        [13., 14.]]])

In [63]:
a4=np.random.randint(10,size=(2,3,4,5))

In [64]:
a4

array([[[[5, 2, 9, 9, 0],
         [8, 5, 9, 7, 0],
         [6, 0, 1, 5, 1],
         [8, 6, 6, 1, 8]],

        [[7, 7, 9, 9, 2],
         [1, 6, 2, 4, 7],
         [0, 3, 1, 7, 2],
         [5, 6, 9, 0, 0]],

        [[4, 1, 6, 7, 0],
         [4, 2, 8, 6, 1],
         [5, 5, 3, 1, 9],
         [8, 7, 0, 2, 7]]],


       [[[9, 6, 9, 5, 3],
         [5, 0, 8, 9, 7],
         [7, 9, 8, 1, 2],
         [0, 6, 4, 6, 3]],

        [[9, 4, 7, 3, 9],
         [1, 8, 8, 8, 0],
         [5, 1, 2, 7, 4],
         [8, 8, 5, 4, 3]],

        [[5, 8, 2, 9, 2],
         [9, 5, 7, 6, 0],
         [7, 5, 9, 0, 2],
         [7, 0, 3, 5, 5]]]])

In [65]:
a4[:,:,:,:1]

array([[[[5],
         [8],
         [6],
         [8]],

        [[7],
         [1],
         [0],
         [5]],

        [[4],
         [4],
         [5],
         [8]]],


       [[[9],
         [5],
         [7],
         [0]],

        [[9],
         [1],
         [5],
         [8]],

        [[5],
         [9],
         [7],
         [7]]]])

## Arithmetic operations on array

In [66]:
a1

array([1, 2, 3])

In [67]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [69]:
a1+ones

array([[2., 3., 4.],
       [2., 3., 4.]])

In [70]:
a3

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.]],

       [[10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]]])

In [71]:
a3.size

18

In [72]:
a3.shape

(2, 3, 3)

In [73]:
a2*a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 